spring.application.name=caller_service
server.port=8080

# Downstream service URL (The Callee)
downstream.base-url=http://localhost:8081/api/unstable

# Retry properties
retry.max-attempts=5
retry.base-delay=100
retry.multiplier=2.0
retry.default-strategy=full-jitter
retry.jitter.full-factor=1.0