spring.application.name=callee_service
server.port=8081

# These MUST start with the prefix "unstable"
unstable.failure-rate=70
unstable.latency-min=50
unstable.latency-max=200

spring.threads.virtual.enabled=true